apiVersion: enterprisesearch.k8s.elastic.co/v1
kind: EnterpriseSearch
metadata:
  name: enterprise-search
spec:
  version: 8.9.2
  count: 1
  elasticsearchRef:
    name: elasticsearch
  config:
    # define the exposed URL at which users will reach Enterprise Search
    ent_search.external_url: https://localhost:3002
    # define the exposed URL at which users will reach Kibana
    kibana.host: https://localhost:5601
    # configure app search document size limit
    app_search.engine.document_size.limit: 100kb
  podTemplate:
    spec:
      containers:
      - name: enterprise-search
        resources:
          requests:
            cpu: 3
            memory: 6Gi
        env:
        - name: JAVA_OPTS
          value: -Xms7500m -Xmx7500m