apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elk-azurefile-sc
provisioner: kubernetes.io/azure-file #file.csi.azure.com #disk.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl